networks:
  proxy:
    external: true

services:
  files:
    image: gtstef/filebrowser:stable
    container_name: files
    networks:
      - proxy
    user: root
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./data:/home/filebrowser/data
      - /:/files
    environment:
      - "FILEBROWSER_CONFIG=data/config.yaml"
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.filebrowser.entrypoints=private
      - traefik.http.services.filebrowser.loadbalancer.server.port=80
