services: 
  prowlarr: 
    image: lscr.io/linuxserver/prowlarr:latest 
    container_name: prowlarr 
    environment: 
      - PUID=1000 
      - PGID=1000 
      - TZ=Europe/London 
    volumes: 
      - ./config:/config 
    ports: 
      - "127.0.0.1:9696:9696"
    restart: unless-stopped
    networks:
      - internal

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    networks: 
      - internal
    environment:
