services:
  audiobookshelf:
    container_name: abs
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - "127.0.0.1:13378:80"
    volumes:
      - /opt/audiobookshelf/audiobooks:/audiobooks
      - /opt/audiobookshelf/podcasts:/podcasts
      - /opt/audiobookshelf/config:/config
      - /opt/audiobookshelf/metadata:/metadata
    restart: unless-stopped
