limit_req_zone $binary_remote_addr zone=goatcounter:10m rate=2r/s;

server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    location = /count.js {
        proxy_pass http://goatcounter:8080/count.js;
        proxy_cache off;
        expires 1h;
        add_header Cache-Control "public, max-age=3600" always;
    }

    location = /count {
        limit_req zone=goatcounter burst=5 nodelay;
        proxy_pass http://goatcounter:8080/count;
        proxy_cache off;
    }
}
