networks:
  proxy:
    external: true

services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    networks:
      - proxy
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - SERVER_HOSTNAMES=nl994.nordvpn.com
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${NORDVPN_PRIVATE_KEY}
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.qbittorrent.rule=Host(`qb.aryam.dev`)
      - traefik.http.routers.qbittorrent.entrypoints=private
      - traefik.http.services.qbittorrent.loadbalancer.server.port=4201 # qBittorrent web UI
      - traefik.http.routers.qbittorrent.service=qbittorrent
      - traefik.http.routers.mousehole.rule=Host(`mousehole.aryam.dev`)
      - traefik.http.routers.mousehole.entrypoints=private
      - traefik.http.services.mousehole.loadbalancer.server.port=5010 # Mousehole web UI
      - traefik.http.routers.mousehole.service=mousehole

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"    # KEY: shares gluetun's network namespace
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=4201
    volumes:
      - ./config:/config
      - /:/host
    depends_on:
      - gluetun
    restart: unless-stopped

  mousehole:
    image: tmmrtn/mousehole:latest
    container_name: mousehole
    network_mode: "service:gluetun"
    environment:
      TZ: Europe/London # Set to your timezone for localization
      MOUSEHOLE_INSECURE_ALLOW_NO_AUTH: true
    volumes:
      # persist cookie data across container restarts
      - "mousehole:/var/lib/mousehole"
    restart: unless-stopped

volumes:
  mousehole:
