---
networks:
  proxy:
    external: true

services:
  dockhand:
    image: fnsys/dockhand:latest
    container_name: dockhand
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dockhand_data:/app/data
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.dockhand.rule=Host(`dockhand.aryam.dev`)
      - traefik.http.routers.dockhand.entrypoints=private
      - traefik.http.routers.dockhand.tls.certresolver=cf
      - traefik.http.services.dockhand.loadbalancer.server.port=3000

volumes:
  dockhand_data:
