---
networks:
  proxy:
    external: true

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    healthcheck:
      disable: true
    environment:
      HOMEPAGE_ALLOWED_HOSTS: home.aryam.dev
    volumes:
      - ./config:/app/config
      - ./images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.rule=Host(`home.aryam.dev`)
      - traefik.http.routers.homepage.entrypoints=private
      - traefik.http.routers.homepage.tls.certresolver=cf
      - traefik.http.services.homepage.loadbalancer.server.port=3000
